### ISSUE TITLE
Go releases require git tags in the format `vX.Y.Z`

### ISSUE THREAD

**Issue by infogulch** [Hellseher/go-shellquote#3]
Hi!

I was just looking for a modularized version of the shellquote library. How serendipitous that I found your repo so soon after you published it!

I noticed you published a release, tag `0.1.0`. However, Go modules require tags to be published in the format `v0.0.0` (note the `v` prefix). If you want to publish the module in a way that is consumable by Go tooling, you should consider tagging with a syntactically valid tag.

Thanks for publishing!

**Comment by Hellseher** [comment]
Re-tagged https://github.com/Hellseher/go-shellquote/releases/tag/v0.1.0

Thanks for the report!

Closing as resolved.
